server:
  port: 8004

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
#
#logging:
#  level:
#    com.example.howtodoinjava: DEBUG

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:9015/douggo
    username: root
    password: mypassword
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: false
server:
  port: 8004

#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:h2:mem:TEST
#    driver-class-name: org.h2.Driver
#    username: username
#    password: password
#    hikari:
#      idle-timeout: 10000

#    spring.jpa.hibernate.ddl-auto=update
#    spring.datasource.url=jdbc:mysql://0.0.0.0:9015/eatshit?useSSL=false
#    spring.datasource.username=root
#    spring.datasource.password=mypassword
#    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
